-- fmp_endgame_tables.sql — run as a privileged role (table owner).
-- Generated by fmp_endgame_harvest.py --print-ddl. app_worker only
-- gets SELECT/INSERT/UPDATE; the harvest never runs DDL.
BEGIN;

CREATE TABLE IF NOT EXISTS fmp_crypto_prices (
  symbol TEXT NOT NULL,
  date DATE NOT NULL,
  open DOUBLE PRECISION,
  high DOUBLE PRECISION,
  low DOUBLE PRECISION,
  close DOUBLE PRECISION,
  volume BIGINT,
  change DOUBLE PRECISION,
  change_percent DOUBLE PRECISION,
  vwap DOUBLE PRECISION,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (symbol, date)
);
GRANT SELECT, INSERT, UPDATE ON fmp_crypto_prices TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_crypto_prices_symbol_idx ON fmp_crypto_prices (symbol);

CREATE TABLE IF NOT EXISTS fmp_transcript_index (
  symbol TEXT NOT NULL,
  year BIGINT NOT NULL,
  quarter BIGINT NOT NULL,
  call_date DATE,
  n_chars BIGINT,
  archive_path TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (symbol, year, quarter)
);
GRANT SELECT, INSERT, UPDATE ON fmp_transcript_index TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_transcript_index_symbol_idx ON fmp_transcript_index (symbol);

CREATE TABLE IF NOT EXISTS fmp_price_target_news (
  row_hash TEXT NOT NULL,
  symbol TEXT,
  published_date TEXT,
  news_url TEXT,
  news_title TEXT,
  analyst_name TEXT,
  price_target DOUBLE PRECISION,
  adj_price_target DOUBLE PRECISION,
  price_when_posted DOUBLE PRECISION,
  news_publisher TEXT,
  news_base_url TEXT,
  analyst_company TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_price_target_news TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_price_target_news_symbol_idx ON fmp_price_target_news (symbol);

CREATE TABLE IF NOT EXISTS fmp_grade_news (
  row_hash TEXT NOT NULL,
  symbol TEXT,
  published_date TEXT,
  news_url TEXT,
  news_title TEXT,
  news_base_url TEXT,
  news_publisher TEXT,
  new_grade TEXT,
  previous_grade TEXT,
  grading_company TEXT,
  action TEXT,
  price_when_posted DOUBLE PRECISION,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_grade_news TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_grade_news_symbol_idx ON fmp_grade_news (symbol);

CREATE TABLE IF NOT EXISTS fmp_historical_market_cap (
  symbol TEXT NOT NULL,
  date DATE NOT NULL,
  market_cap BIGINT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (symbol, date)
);
GRANT SELECT, INSERT, UPDATE ON fmp_historical_market_cap TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_historical_market_cap_symbol_idx ON fmp_historical_market_cap (symbol);

CREATE TABLE IF NOT EXISTS fmp_index_constituents (
  index_name TEXT NOT NULL,
  symbol TEXT NOT NULL,
  name TEXT,
  sector TEXT,
  sub_sector TEXT,
  headquarter TEXT,
  date_first_added TEXT,
  cik TEXT,
  founded TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (index_name, symbol)
);
GRANT SELECT, INSERT, UPDATE ON fmp_index_constituents TO app_worker;

CREATE TABLE IF NOT EXISTS fmp_index_constituent_changes (
  row_hash TEXT NOT NULL,
  index_name TEXT,
  date_added TEXT,
  added_security TEXT,
  removed_ticker TEXT,
  removed_security TEXT,
  date TEXT,
  symbol TEXT,
  reason TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_index_constituent_changes TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_index_constituent_changes_index_name_idx ON fmp_index_constituent_changes (index_name);

CREATE TABLE IF NOT EXISTS fmp_economic_calendar (
  row_hash TEXT NOT NULL,
  event_date TEXT,
  country TEXT,
  event TEXT,
  currency TEXT,
  previous DOUBLE PRECISION,
  estimate DOUBLE PRECISION,
  actual DOUBLE PRECISION,
  change DOUBLE PRECISION,
  impact TEXT,
  change_percentage DOUBLE PRECISION,
  unit TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_economic_calendar TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_economic_calendar_event_date_idx ON fmp_economic_calendar (event_date);

CREATE TABLE IF NOT EXISTS fmp_dcf (
  symbol TEXT NOT NULL,
  date DATE NOT NULL,
  dcf DOUBLE PRECISION,
  levered_dcf DOUBLE PRECISION,
  stock_price DOUBLE PRECISION,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (symbol, date)
);
GRANT SELECT, INSERT, UPDATE ON fmp_dcf TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_dcf_symbol_idx ON fmp_dcf (symbol);

CREATE TABLE IF NOT EXISTS fmp_mergers_acquisitions (
  row_hash TEXT NOT NULL,
  symbol TEXT,
  company_name TEXT,
  cik TEXT,
  targeted_company TEXT,
  targeted_cik TEXT,
  targeted_symbol TEXT,
  transaction_date DATE,
  accepted_date TEXT,
  link TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_mergers_acquisitions TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_mergers_acquisitions_symbol_idx ON fmp_mergers_acquisitions (symbol);

CREATE TABLE IF NOT EXISTS fmp_ipos_calendar (
  symbol TEXT NOT NULL,
  date DATE NOT NULL,
  company TEXT,
  exchange TEXT,
  actions TEXT,
  shares BIGINT,
  price_range TEXT,
  market_cap BIGINT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (symbol, date)
);
GRANT SELECT, INSERT, UPDATE ON fmp_ipos_calendar TO app_worker;

CREATE TABLE IF NOT EXISTS fmp_etf_holdings (
  etf TEXT NOT NULL,
  asset TEXT NOT NULL,
  name TEXT,
  isin TEXT,
  cusip TEXT,
  shares DOUBLE PRECISION,
  weight_percentage DOUBLE PRECISION,
  market_value DOUBLE PRECISION,
  updated_at TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (etf, asset)
);
GRANT SELECT, INSERT, UPDATE ON fmp_etf_holdings TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_etf_holdings_etf_idx ON fmp_etf_holdings (etf);

CREATE TABLE IF NOT EXISTS fmp_etf_weightings (
  etf TEXT NOT NULL,
  kind TEXT NOT NULL,
  label TEXT NOT NULL,
  weight_percentage DOUBLE PRECISION,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (etf, kind, label)
);
GRANT SELECT, INSERT, UPDATE ON fmp_etf_weightings TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_etf_weightings_etf_idx ON fmp_etf_weightings (etf);

CREATE TABLE IF NOT EXISTS fmp_sec_filings (
  row_hash TEXT NOT NULL,
  symbol TEXT,
  cik TEXT,
  filing_date TEXT,
  accepted_date TEXT,
  form_type TEXT,
  has_financials TEXT,
  link TEXT,
  final_link TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_sec_filings TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_sec_filings_symbol_idx ON fmp_sec_filings (symbol);

CREATE TABLE IF NOT EXISTS fmp_index_prices (
  symbol TEXT NOT NULL,
  date DATE NOT NULL,
  open DOUBLE PRECISION,
  high DOUBLE PRECISION,
  low DOUBLE PRECISION,
  close DOUBLE PRECISION,
  volume BIGINT,
  change DOUBLE PRECISION,
  change_percent DOUBLE PRECISION,
  vwap DOUBLE PRECISION,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (symbol, date)
);
GRANT SELECT, INSERT, UPDATE ON fmp_index_prices TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_index_prices_symbol_idx ON fmp_index_prices (symbol);

CREATE TABLE IF NOT EXISTS fmp_delisted_companies (
  row_hash TEXT NOT NULL,
  symbol TEXT,
  company_name TEXT,
  exchange TEXT,
  ipo_date DATE,
  delisted_date DATE,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source VARCHAR(16) NOT NULL DEFAULT 'fmp',
  PRIMARY KEY (row_hash)
);
GRANT SELECT, INSERT, UPDATE ON fmp_delisted_companies TO app_worker;
CREATE INDEX IF NOT EXISTS fmp_delisted_companies_symbol_idx ON fmp_delisted_companies (symbol);

-- forex top-up reuses the existing fmp_forex table:
GRANT SELECT, INSERT, UPDATE ON fmp_forex TO app_worker;

COMMIT;
